# frozen_string_literal: true

require "mini_paperclip/shoulda/matchers/have_attached_file_matcher"
require "mini_paperclip/shoulda/matchers/validate_attachment_content_type_matcher"
require "mini_paperclip/shoulda/matchers/validate_attachment_geometry_matcher"
require "mini_paperclip/shoulda/matchers/validate_attachment_presence_matcher"
require "mini_paperclip/shoulda/matchers/validate_attachment_size_matcher"
