# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.5
          - 2.6
          - 2.7
        gemfile:
          - gemfiles/rails_52.gemfile
          - gemfiles/rails_60.gemfile
          - gemfiles/rails_head.gemfile
        exclude:
          - ruby: 2.5
            gemfile: gemfiles/rails_head.gemfile
          - ruby: 2.6
            gemfile: gemfiles/rails_head.gemfile
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install -j 3 -r 6 --gemfile=${{ matrix.gemfile }}
    - name: Run tests and Print coverage
      env:
        COVERAGE: 1
        LOGLEVEL: info
      run: bundle exec --gemfile=${{ matrix.gemfile }} rake
